#pragma once

#include <Geode/Geode.hpp>

namespace augment::fonts {

// GD's own bigFont / goldFont / chatFont have no Hangul, so every label that
// can show augment text uses one of these. The charset of all of them is
// rebuilt from the string literals in src/ by scripts/fontcharset.ps1 (run by
// build.ps1), so any Korean literal in src/ is guaranteed to have a glyph.
//
// Sizes are the UHD size; sd is a quarter of it, like GD's own fonts.
//   Name / Text: ImcreSoojin with a baked black outline + drop shadow, white
//                glyphs (tint with setColor; the outline stays black). Baked
//                by scripts/fontgen.py because Geode's font generator ignores
//                its "outline" key. sd 24 px (goldFont-sized) / 16 px
//                (chatFont-sized). All player-facing UI.
//   Debug:       Pretendard Regular, plain, sd 16 px, generated by Geode from
//                mod.json — HUD debug lines only.
constexpr char const* Name = "AugName.fnt"_spr;
constexpr char const* Text = "AugText.fnt"_spr;
constexpr char const* Debug = "AugDebug.fnt"_spr;

} // namespace augment::fonts
